# DISKRITISASI

1. Carilah data yang bertipe numerik
2. Lakukan proses diskritisasi dengan equal width dan equal frequency
3. Lakukan proses diskritisasi dengan basic entropy

*Discretization atau binning digunakan untuk mengubah atribut numerik menjadi atribut kategorikal.* Perubahan tersebut dilakukan dengan mengkategorikan atribut numerik menjadi beberapa tingkatan atribut kategorikal. Sebagai contoh, apabila terdapat data numerik dengan data berikut:

$$ 2, 4, 10, 17, 5, 23, 11, 48, 35, 56, 20$$

Maka, dengan discretization, data tersebut dapat dikategorikan menjadi dua kelompok:

$$Kelompok\ 1 (Dibawah\ 25): 2, 4, 5,10, 11, 17, 20, 23$$

$$Kelompok\ 2 (Diatas\ 25): 35, 48, 56$$

*Mengubah data numerik menjadi kategorikal memungkinkan data tersebut untuk dianalisis dengan menggunakan analisis kategorikal. Sehingga, informasi baru bisa didapatkan dari data tersebut.*

sumber data bunga

In [1]:
#Datasets iris
import pandas as pd
import numpy as np
from math import log2
import statistics as st
pd.options.mode.chained_assignment=None

url='https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
pd.read_csv(url)
df = pd.read_csv(url)
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [2]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = df["sepal_length"]
SEPAL_WIDTH_SERIES = df["sepal_width"]
PETAL_LENGTH_SERIES = df["petal_length"]
PETAL_WIDTH_SERIES = df["petal_width"]

# Class Variety Name 
IRIS_VARIETY = df["species"]

**a. Equal Width**

*Equal-width adalah algoritma untuk membagi rentang dari X menjadi k interval dengan ukuran lebar yang sama*

Method cut digunakan untuk mencari interval menggunakan metode equal-width interval

*Syntax*<br>
pd.cut(series, interval, right=True, label)

*   Sepal Width

sepal width berdasarkan lebar kelompak bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [3]:
# interval equal_width
# ew = equal_width

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal_width
sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [4]:
# dataframe dari sepal_widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_sepal_width_ew = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning, IRIS_VARIETY), axis=1))

In [5]:
# merubah nama kolom
df_sepal_width_ew.columns = ["sepal.width", "category", "species"]

In [6]:
df_sepal_width_ew

     sepal.width       category    species
0            3.5          lebar     setosa
1            3.0          lebar     setosa
2            3.2          lebar     setosa
3            3.1          lebar     setosa
4            3.6          lebar     setosa
..           ...            ...        ...
145          3.0          lebar  virginica
146          2.5  sedikit_lebar  virginica
147          3.0          lebar  virginica
148          3.4          lebar  virginica
149          3.0          lebar  virginica

[150 rows x 3 columns]

In [7]:
#jumlah data sepal_width berdasarkan label
labelled_sepal_width_ew_binning

lebar            88
sedikit_lebar    47
sangat_lebar     15
Name: sepal_width, dtype: int64

In [8]:
#jumlah data sepal_width berdasarkan interval
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

* Petal Width

petal width berdasarkan lebar mahkota bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [9]:
# interval equal-width
# ew = equal-width

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-width
petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [10]:
# dataframe dari petal_widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_petal_width = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ew_binning, IRIS_VARIETY), axis=1))

In [11]:
# cmengubah nama kolom
df_petal_width.columns = ["petal.width", "category", "species"]

In [12]:
df_petal_width

     petal.width       category    species
0            0.2  sedikit_lebar     setosa
1            0.2  sedikit_lebar     setosa
2            0.2  sedikit_lebar     setosa
3            0.2  sedikit_lebar     setosa
4            0.2  sedikit_lebar     setosa
..           ...            ...        ...
145          2.3   sangat_lebar  virginica
146          1.9   sangat_lebar  virginica
147          2.0   sangat_lebar  virginica
148          2.3   sangat_lebar  virginica
149          1.8   sangat_lebar  virginica

[150 rows x 3 columns]

In [13]:
#jumlah data petal_width berdasarkan label
labelled_petal_width_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal_width, dtype: int64

In [14]:
#jumlah data petal_width berdasarkan interval
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal_width, dtype: int64

* Sepal Length

sepal length berdasarkan panjang kelompak bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [15]:
# interval equal-width
# ew = equal-width

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-width
sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [16]:
# dataframe dari sepal_length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_sepal_length_ew = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ew_binning, IRIS_VARIETY), axis=1))

In [17]:
# mengganti nama kolom
df_sepal_length_ew.columns = ["sepal_length", "category", "species"]

In [18]:
df_sepal_length_ew

     sepal_length       category    species
0             5.1  sedikit_lebar     setosa
1             4.9  sedikit_lebar     setosa
2             4.7  sedikit_lebar     setosa
3             4.6  sedikit_lebar     setosa
4             5.0  sedikit_lebar     setosa
..            ...            ...        ...
145           6.7          lebar  virginica
146           6.3          lebar  virginica
147           6.5          lebar  virginica
148           6.2          lebar  virginica
149           5.9          lebar  virginica

[150 rows x 3 columns]

In [19]:
#jumlah data sepal_length berdasarkan label
labelled_sepal_length_ew_binning

lebar            71
sedikit_lebar    59
sangat_lebar     20
Name: sepal_length, dtype: int64

In [20]:
#jumlah data sepal_length berdasarkan interval
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal_length, dtype: int64

* Petal Length

petal length berdasarkan panjang mahkota bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [21]:
# interval equal-width
# ew = equal-width

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-width
petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [22]:
# dataframe dari petal_length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_petal_length_ew =  pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES,petal_length_ew_binning, IRIS_VARIETY), axis=1))

In [23]:
# mengubah nama kolom
df_petal_length_ew.columns = ["petal_length", "category", "species"]

In [24]:
df_petal_length_ew

     petal_length       category    species
0             1.4  sedikit_lebar     setosa
1             1.4  sedikit_lebar     setosa
2             1.3  sedikit_lebar     setosa
3             1.5  sedikit_lebar     setosa
4             1.4  sedikit_lebar     setosa
..            ...            ...        ...
145           5.2   sangat_lebar  virginica
146           5.0   sangat_lebar  virginica
147           5.2   sangat_lebar  virginica
148           5.4   sangat_lebar  virginica
149           5.1   sangat_lebar  virginica

[150 rows x 3 columns]

In [25]:
#jumlah data petal_length berdasarkan label
labelled_petal_length_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal_length, dtype: int64

In [26]:
#jumlah data petal.length berdasarkan interval
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal_length, dtype: int64

In [27]:
SEPAL_LENGTH_SERIES["Kategori"] = pd.cut(df["sepal_length"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
SEPAL_WIDTH_SERIES["Kategori"] = pd.cut(df["sepal_width"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
PETAL_LENGTH_SERIES['Kategori'] = pd.cut(df["petal_length"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
PETAL_WIDTH_SERIES['Kategori'] = pd.cut(df["petal_width"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])

equalWidth = pd.DataFrame([])
equalWidth["sepal.length"] = df["sepal_length"]
equalWidth['sepal_length_category'] = SEPAL_LENGTH_SERIES["Kategori"]

equalWidth["sepal.width"] = df["sepal_width"]
equalWidth["sepal_width_category"] = SEPAL_WIDTH_SERIES["Kategori"]

equalWidth["petal.length"] = df["petal_length"]
equalWidth["petal_length_category"] = PETAL_LENGTH_SERIES["Kategori"]

equalWidth["petal.width"] = df["petal_width"]
equalWidth["petal_width_category"] = PETAL_WIDTH_SERIES["Kategori"]

equalWidth["species"] = df[["species"]]

equalWidth

,sepal.length,sepal_length_category,sepal.width,sepal_width_category,petal.length,petal_length_category,petal.width,petal_width_category,species
0,5.1,sedikit_lebar,3.5,lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
1,4.9,sedikit_lebar,3.0,lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
2,4.7,sedikit_lebar,3.2,lebar,1.3,sedikit_lebar,0.2,sedikit_lebar,setosa
3,4.6,sedikit_lebar,3.1,lebar,1.5,sedikit_lebar,0.2,sedikit_lebar,setosa
4,5.0,sedikit_lebar,3.6,lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,lebar,3.0,lebar,5.2,sangat_lebar,2.3,sangat_lebar,virginica
146,6.3,lebar,2.5,sedikit_lebar,5.0,sangat_lebar,1.9,sangat_lebar,virginica
147,6.5,lebar,3.0,lebar,5.2,sangat_lebar,2.0,sangat_lebar,virginica
148,6.2,lebar,3.4,lebar,5.4,sangat_lebar,2.3,sangat_lebar,virginica
149,5.9,lebar,3.0,lebar,5.1,sangat_lebar,1.8,sangat_lebar,virginica

**b. Equal Frekuensi Interval**

*Equal frekuensi interval adalah algoritma untuk membagi rentang dari X menjadi rentang-rentang yang berisi nilai data yang kurang lebih nilainya sama*

pandas menyediakan qcut untuk mencari nilai interval dari Equal-Frequency Intervals

```
# Syntax
pd.qcut(series, interval, label)
```

* Sepal Width

Sepal width berdasarkan lebar kelopak bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [28]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = df["sepal_length"]
SEPAL_WIDTH_SERIES = df["sepal_width"]
PETAL_LENGTH_SERIES = df["petal_length"]
PETAL_WIDTH_SERIES = df["petal_width"]

# Class Variety Name 
IRIS_VARIETY = df["species"]

In [29]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-frequency
sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [30]:
# dataframe dari sepal_widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_sepal_width_ef = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning, IRIS_VARIETY), axis = 1))

In [31]:
# mengubah nama kolom
df_sepal_width_ef.columns = ["sepal_width", "category", "variety"]

In [32]:
df_sepal_width_ef

     sepal_width       category    variety
0            3.5   sangat_lebar     setosa
1            3.0          lebar     setosa
2            3.2          lebar     setosa
3            3.1          lebar     setosa
4            3.6   sangat_lebar     setosa
..           ...            ...        ...
145          3.0          lebar  virginica
146          2.5  sedikit_lebar  virginica
147          3.0          lebar  virginica
148          3.4   sangat_lebar  virginica
149          3.0          lebar  virginica

[150 rows x 3 columns]

In [33]:
#jumlah data sepal_width berdasarkan label
labelled_sepal_width_ef_binning

sedikit_lebar    57
lebar            51
sangat_lebar     42
Name: sepal_width, dtype: int64

In [34]:
#jumlah data sepal.width berdasarkan interval
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepal_width, dtype: int64

* Petal Width

petal width berdasarkan lebar mahkota bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [35]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)


petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [36]:
# dataframe dari petal_widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_petal_width_ef = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning, IRIS_VARIETY), axis = 1))

In [37]:
# mengubah nama kolom
df_petal_width_ef.columns = ["petal_width", "category", "variety"]

In [38]:
df_petal_width_ef

     petal_width       category    variety
0            0.2  sedikit_lebar     setosa
1            0.2  sedikit_lebar     setosa
2            0.2  sedikit_lebar     setosa
3            0.2  sedikit_lebar     setosa
4            0.2  sedikit_lebar     setosa
..           ...            ...        ...
145          2.3   sangat_lebar  virginica
146          1.9   sangat_lebar  virginica
147          2.0   sangat_lebar  virginica
148          2.3   sangat_lebar  virginica
149          1.8   sangat_lebar  virginica

[150 rows x 3 columns]

In [39]:
#jumlah data petal_width berdasarkan label
labelled_petal_width_ef_binning

lebar            52
sedikit_lebar    50
sangat_lebar     48
Name: petal_width, dtype: int64

In [40]:
#jumlah data petal.width berdasarkan interval
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal_width, dtype: int64

* Sepal Length

sepal length berdasarkan panjang kelopak bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [41]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-frequency
sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [42]:
# dataframe dari sepal_length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_sepal_length_ef = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning, IRIS_VARIETY), axis=1))

In [43]:
# mengubah nama kolom
df_sepal_length_ef.columns = ["sepal_length", "category", "variety"]

In [44]:
df_sepal_length_ef

     sepal_length       category    variety
0             5.1  sedikit_lebar     setosa
1             4.9  sedikit_lebar     setosa
2             4.7  sedikit_lebar     setosa
3             4.6  sedikit_lebar     setosa
4             5.0  sedikit_lebar     setosa
..            ...            ...        ...
145           6.7   sangat_lebar  virginica
146           6.3          lebar  virginica
147           6.5   sangat_lebar  virginica
148           6.2          lebar  virginica
149           5.9          lebar  virginica

[150 rows x 3 columns]

In [45]:
#jumlah data sepal_length berdasarkan label
labelled_sepal_length_ef_binning

lebar            56
sedikit_lebar    52
sangat_lebar     42
Name: sepal_length, dtype: int64

In [46]:
#jumlah data sepal_length berdasarkan interval
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal_length, dtype: int64

* Petal Length

petal length berdasarkan panjang mahkota bunga iris dikelompokkan menjadi 3:
1.   sedikit lebar
2.   lebar
3.   sangat lebar

In [47]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
# Untuk menghitung banyaknya kategori label
amount_of_binning = len(labels)

# untuk menghitung interval equal-frequency
petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [48]:
# dataframe dari petal_length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_petal_length_ef = pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning, IRIS_VARIETY), axis=1))

In [49]:
# mengubah nama kolom
df_petal_length_ef.columns = ["petal_length", "category", "variety"]

In [50]:
df_petal_length_ef

     petal_length       category    variety
0             1.4  sedikit_lebar     setosa
1             1.4  sedikit_lebar     setosa
2             1.3  sedikit_lebar     setosa
3             1.5  sedikit_lebar     setosa
4             1.4  sedikit_lebar     setosa
..            ...            ...        ...
145           5.2   sangat_lebar  virginica
146           5.0   sangat_lebar  virginica
147           5.2   sangat_lebar  virginica
148           5.4   sangat_lebar  virginica
149           5.1   sangat_lebar  virginica

[150 rows x 3 columns]

In [51]:
#jumlah data petal_length berdasarkan label
labelled_petal_length_ef_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal_length, dtype: int64

In [52]:
#jumlah data petal_length berdasarkan interval
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal_length, dtype: int64

In [53]:
SEPAL_LENGTH_SERIES["Kategori"] = pd.qcut(df["sepal_length"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
SEPAL_WIDTH_SERIES["Kategori"] = pd.qcut(df["sepal_width"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
PETAL_LENGTH_SERIES['Kategori'] = pd.qcut(df["petal_length"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])
PETAL_WIDTH_SERIES['Kategori'] = pd.qcut(df["petal_width"],3, labels = ["sedikit_lebar", "lebar", "sangat_lebar"])

equalFrequency = pd.DataFrame([])
equalFrequency["sepal.length"] = df["sepal_length"]
equalFrequency['sepal_length_category'] = SEPAL_LENGTH_SERIES["Kategori"]

equalFrequency["sepal.width"] = df["sepal_width"]
equalFrequency["sepal_width_category"] = SEPAL_WIDTH_SERIES["Kategori"]

equalFrequency["petal.length"] = df["petal_length"]
equalFrequency["petal_length_category"] = PETAL_LENGTH_SERIES["Kategori"]

equalFrequency["petal.width"] = df["petal_width"]
equalFrequency["petal_width_category"] = PETAL_WIDTH_SERIES["Kategori"]

equalFrequency["variety"] = df[["species"]]

equalFrequency

,sepal.length,sepal_length_category,sepal.width,sepal_width_category,petal.length,petal_length_category,petal.width,petal_width_category,variety
0,5.1,sedikit_lebar,3.5,sangat_lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
1,4.9,sedikit_lebar,3.0,lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
2,4.7,sedikit_lebar,3.2,lebar,1.3,sedikit_lebar,0.2,sedikit_lebar,setosa
3,4.6,sedikit_lebar,3.1,lebar,1.5,sedikit_lebar,0.2,sedikit_lebar,setosa
4,5.0,sedikit_lebar,3.6,sangat_lebar,1.4,sedikit_lebar,0.2,sedikit_lebar,setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,sangat_lebar,3.0,lebar,5.2,sangat_lebar,2.3,sangat_lebar,virginica
146,6.3,lebar,2.5,sedikit_lebar,5.0,sangat_lebar,1.9,sangat_lebar,virginica
147,6.5,sangat_lebar,3.0,lebar,5.2,sangat_lebar,2.0,sangat_lebar,virginica
148,6.2,lebar,3.4,sangat_lebar,5.4,sangat_lebar,2.3,sangat_lebar,virginica
149,5.9,lebar,3.0,lebar,5.1,sangat_lebar,1.8,sangat_lebar,virginica

ENTROPY

*Entropi merupakan distribusi probabilitas dalam teori informasi dan diadopsi kedalam Algoritme C4.5 untuk mengukur tingkat homogenitas distribusi kelas dari sebuah himpunan data (dataset).* <br>Sebagai ilustrasi, semakin tinggi tingkat entropi dari sebuah dataset maka semakin homogen distribusi kelas pada dataset tersebut. Persamaan untuk menghitung entropi pada pohon keputusan C4.5 ditunjukan pada Persamaan 1 (Raditya, 2009):

$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{k} -phi \ log_{2} \ phi \\
Keterangan &: \\
S &= Himpunan \ dataset  \\
k &= Banyaknya \ partisi \ S \\
phi &= Proporsi \ S_{i} \ terhadap \ S
\end{align*}
$$

Persiapan

* Impor modul log2 dari *package math*
* Ambil data yang akan digunakan


```
# dataframe yang berisi petal.width ( Equal Frequency Interval)
df_petal_width_ef
```

* Membuat Kategory


```
labels = ['sedikit_lebar', 'lebar', 'sangat_lebar']
```

In [54]:
# dataframe yang akan digunakan (Equeal Frequency Interval)
df_petal_width_ef

     petal_width       category    variety
0            0.2  sedikit_lebar     setosa
1            0.2  sedikit_lebar     setosa
2            0.2  sedikit_lebar     setosa
3            0.2  sedikit_lebar     setosa
4            0.2  sedikit_lebar     setosa
..           ...            ...        ...
145          2.3   sangat_lebar  virginica
146          1.9   sangat_lebar  virginica
147          2.0   sangat_lebar  virginica
148          2.3   sangat_lebar  virginica
149          1.8   sangat_lebar  virginica

[150 rows x 3 columns]

*   Tentukan label

In [55]:
# label kategori
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]

In [56]:
# dataframe
target_data = df_petal_width_ef
target_data

     petal_width       category    variety
0            0.2  sedikit_lebar     setosa
1            0.2  sedikit_lebar     setosa
2            0.2  sedikit_lebar     setosa
3            0.2  sedikit_lebar     setosa
4            0.2  sedikit_lebar     setosa
..           ...            ...        ...
145          2.3   sangat_lebar  virginica
146          1.9   sangat_lebar  virginica
147          2.0   sangat_lebar  virginica
148          2.3   sangat_lebar  virginica
149          1.8   sangat_lebar  virginica

[150 rows x 3 columns]

In [57]:
# category label
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]

Functions

Fungsi menghitung banyaknya data setiap kategori

In [58]:
#fungsi yang digunakan untuk menghitung banyaknya data berdasarkan kategori
def countEveryCategory(data_column, labels, column, category):
    group = data_column.groupby(category).count()
    amount_of_every_category = []
    for label in labels:
        amount_of_every_category.append(group.loc[label, column])
    return amount_of_every_category

Fungsi menghitung banyaknya data setiap kategori berdasarkan nilai pembagi atau split value yang diberikan

In [59]:
# menghitung banyaknya data dari setiap kategori berdasarkan split value
def split(split_value, data_column, labels, col, category):
    less_group = data_column[data_column[col] < split_value]
    greater_group = data_column[data_column[col] >= split_value]
    
    length_less_group = countEveryCategory(less_group, labels, col, category)
    length_greater_group = countEveryCategory(greater_group, labels, col, category)
    
    return (length_less_group, length_greater_group)

Setelah membagi dataset berdasarkan sebuah atribut kedalam subset yang lebih kecil, entropi dari data tersebut akan berubah. Perubahan entropi ini dapat digunakan untuk menentukan bagus tidaknya pembagian data yang telah dilakukan. Perubahan entropi ini disebut dengan information gain dalam Algoritme C4.5. Information gain ini diukur dengan menghitung selisih antara entropi dataset sebelum dan sesudah pembagian (splitting) dilakukan. Pembagian yang terbaik
akan menghasilkan entropi subset yang paling kecil, dengan demikian berdampak pada information gain yang terbesar.

Fungsi menghitung perbedaan gain antara entropi inisial dengan entropi nilai pembagi yang diberikan




$$Gain(E_{new}) = (E_{initial}) \ - (E_{new})$$

In [60]:
# count information gain from inisial entropy and new entropy
def count_gain(inisial_entropy, new_entropy):
  return inisial_entropy - new_entropy

Fungsi menghitung entropy

In [61]:
# count entropy
def count_entropy(data_target):
    all_prob = []
    for prob in data_target:
        if (prob/sum(data_target) != 0):
            all_prob.append(prob/sum(data_target) * log2(prob/sum(data_target)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

Fungsi menghitung Info entropy berdasarkan nilai pembagi atau split value yang diberikan


$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [62]:
# count entropy for given a split value
def info(d, data_target):
    temp = []
    for value in d:
        temp.append((sum(value) / data_target.shape[0]) * count_entropy(value))
    return sum(temp)

Implementasi
*   Hitung target entropy
*   Hitung target entropy dengan split value
*   Hitung entropy gain



*   **Entropy inisial atau awal**

In [63]:
# entropy data target
initial_data_target_entropy = count_entropy(countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1]))



*   **Entropy uji coba 1**
*   Nilai *split* yaitu 0.7
*   Data kurang dari $ < 0.7 $
*   Data kurang dari $ >= 0.7 $

In [64]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_target_1 = info(split(0.7, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)



*   **Entropy uji coba 2**
*   Nilai *split* yaitu $ 1.4 $
*   Data kurang dari $ < 1.4 $
*   Data kurang dari $ >= 1.4 $

In [65]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_target_2 = info(split(1.4, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)



*   **Entropy uji coba 3**
*   Nilai *split* yaitu $ 2.1 $
*   Data kurang dari $ < 2.1 $
*   Data kurang dari $ >= 2.1 $

In [66]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_target_3 = info(split(2.1, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 1})$

In [67]:
# information gain (entropy data target and entropy_data_target_1)
count_gain(initial_data_target_entropy, entropy_data_target_1)

0.9182958340544896

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 2})$

In [68]:
# information gain (entropy data target and entropy_data_target_2)
count_gain(initial_data_target_entropy, entropy_data_target_2)

0.6536600192724277

$Gain(E_{new}) = (E_{initial}) \ - (E_{target\ data\ 3})$

In [69]:
# information gain (entropy data target and entropy_data_target_3)
count_gain(initial_data_target_entropy, entropy_data_target_3)

0.2985203537604644